### ISSUE TITLE
Fails to build with caddy 2.8.1

### ISSUE THREAD

**Issue by major** [libdns/porkbun#7]
I had an update from Renovate in major/caddy#26 to update caddy to 2.8.1, but the update [failed](https://github.com/major/caddy/actions/runs/9324696232/job/25670414543?pr=26):

```
#9 27.01 2024/05/31 21:46:02 [INFO] exec (timeout=0s): /usr/local/go/bin/go build -o /usr/bin/caddy -ldflags -w -s -trimpath -tags nobadger 
#9 40.92 # github.com/libdns/porkbun
#9 40.92 /go/pkg/mod/github.com/libdns/porkbun@v0.1.2/models.go:51:13: cannot use priority (variable of type int) as uint value in struct literal
#9 76.33 2024/05/31 21:46:52 [INFO] Skipping cleanup as requested; leaving folder intact: /tmp/buildenv_2024-05-31-2145.1412197892
#9 76.33 2024/05/31 21:46:52 [FATAL] exit status 1
```

The [dockerfile](https://github.com/major/caddy/blob/main/Dockerfile) is unchanged from previous caddy versions.

**Comment by Monviech** [comment]
You have to build it like this currently until there are new version tags released.

https://github.com/opnsense/tools/blob/e8419e95126ba4b2641d75241398dd217090dda0/config/24.1/make.conf#L105-L106

Pass both the caddy-dns and libdns versions of porkbun explicitely.

**Comment by major** [comment]
Thanks for the workaround! That worked out well. 👏

**Comment by Niallfitzy1** [comment]
v0.1.3 has been published that fixes this
