### ISSUE TITLE
API Hostname Update

### ISSUE THREAD

**Issue by bdr99** [libdns/porkbun#8]
I received this email from Porkbun today:

> Hello there,
>
> The reason you are receiving this email is because you have an API key associated with your account. In order to ensure that any apps or tools you may have that utilize our API, we wanted to let you know about some upcoming critical updates.
>
> We know these kinds of changes are annoying but the time has come to separate the processing of incoming API commands from our website. In previous documentation the hostname porkbun.com was used for the API but we have recently updated it to api.porkbun.com and in the near future will start enforcing its use. Please update the hostname for our API to api.porkbun.com as soon as possible. 
>
> **CRITICAL UPDATE DETAILS**
> **Type**: API Hostname Change
> **Old Value**: porkbun.com
> **New Value**: api.porkbun.com
> Deadline: 2024-12-01 00:00:00 UTC
>
> Please note that after the deadline, API calls made to the old hostname will no longer be allowed. If you have any questions or concerns please contact support. 
>
> Thank you,
> The Porkbun Team

It seems this library will break soon if it is not updated to use the new hostname.

**Comment by Niallfitzy1** [comment]
This was fixed in #10 (and was also tracked in #9)
